name: lets-plot-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - bs4
  - colorcet
  - geopandas
  - jupyter_sphinx
  - numpy
  - pandas
  - pip
  - pytest
  - selenium
  - sphinx
  - sphinx-panels
  - pip:
    - sphinx_bootstrap_theme
    - sphinx-reredirects
    - lets_plot