name: lets-plot-docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bs4
  - cairosvg
  - cartopy
  - gdal=3.5.0
  - geopandas
  - jupyter
  - jupyter_sphinx
  - numpy
  - numpydoc
  - pandas
  - pip
  - polars
  - pyarrow
  - pydata-sphinx-theme
  - pyogrio
  - pyshp
  - pytest
  - selenium
  - sphinx
  - sphinx-design
  - statsmodels
  - pip:
    - lets_plot
    - shapely>=2.0.0