name: lets-plot-docs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bs4
  - cartopy
  - geopandas
  - jupyter
  - jupyter_sphinx
  - numpy
  - numpydoc
  - pandas
  - pip
  - pytest
  - selenium
  - sphinx
  - sphinx-panels
  - statsmodels
  - pip:
    - sphinx_bootstrap_theme
    - lets_plot